---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest

inputs:
  - name: concourse_pipelien1
  - name: dependency-cache

run:
  path: concourse_pipelien1/ci/scripts/run_tests.sh